version: "3"

services: 
  api:
    build: ./api
    container_name: "flask_api"
    ports:
      - "5000:5000"
    environment: 
      - FLASK_RUN_PORT="5000"
      - FLASK_ENV="development"
  gui:
    build: ./gui
    container_name: "flask_gui"
    ports:
      - "8000:8000"
    environment: 
      - FLASK_RUN_PORT="8000"
      - FLASK_ENV="development"

